driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: default
  run_list:
  - recipe[postfix]

- name: aliases
  run_list:
  - recipe[postfix::aliases]

- name: client
  run_list:
  - recipe[postfix::client]

- name: server
  run_list:
  - recipe[postfix::server]

- name: sasl_auth
  run_list:
  - recipe[postfix::sasl_auth]
  attributes:
    postfix:
      main:
        relayhost: "localhost"
        smtp_sasl_auth_enable: "yes"
      sasl:
        smtp_sasl_user_name: "kitchenuser"
        smtp_sasl_passwd: "not-a-real-thing"
